### PR TITLE
fix streaming

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by dkhamsing** [comment]
@brightsider thx for the pull

can u see what is wrong in the demo? streaming has this error

```
Streaming
2016-09-07 07:40:19.482 FHSTwitterEngine[76163:13322984] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2016-09-07 07:40:19.485 FHSTwitterEngine[76163:13321976] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." 
```

**Comment by brightsider** [comment]
I think this is error of transport security.

**Comment by dkhamsing** [comment]
Ah thanks

**Comment by dkhamsing** [comment]
thank you again!

**Pull request merged**
