### PR TITLE
Cocoapods support, changed project structure and added all pods requirements

### PR DESCRIPTION
**Pull request by salah-ghanim**
Restructured the project to fit default cocoapods default structure for libraries. 

Kept the current example in sample folder. 

Moved source code to src directory

Added project dependancies, license, and all necessary details to the podspec file

### CODE REVIEW

**Comment by dkhamsing** [comment]
@salah-ghanim can you resolve the conflicts?

**Comment by dkhamsing** [comment]
Closing for now. Let me know if you would like to revisit this.
:sweat_smile:

**Comment by salah-ghanim** [comment]
hey @dkhamsing sorry that I didn't respond earlier. I've been meaning to fix the conflict for a while.

Its just been a while since I did these changes, and the conflict size is quit big.

Anyway, I can get them done this weekend.

**Comment by dkhamsing** [comment]
Oh cool, will reopen

**Comment by salah-ghanim** [comment]
@dkhamsing 

Once you merge with master you can modify the repo's url inside the podspec file to point to your rep

so
```
  s.source = { :git => "https://github.com/salah-ghanim/FHSTwitterEngine.git", :tag => s.version.to_s }
```
should become 

```
  s.source = { :git => "https://github.com/fhsjaagshs/FHSTwitterEngine.git", :tag => s.version.to_s }
```

PS also double check the tags/versions

**Comment by dkhamsing** [comment]
Will take a look thank you

**Comment by dkhamsing** [comment]
Note `update_with_media deprecated` #92

**Pull request merged**
